# Generated by Django 5.1.2 on 2024-11-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomzod ismi')),
                ('date_of_birth', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('address', models.CharField(max_length=500, verbose_name='Nomzod Manzili')),
                ('experience', models.CharField(max_length=500, verbose_name='Tajriba yili')),
                ('experience_name', models.CharField(max_length=600, verbose_name='Qaysi sohalarda ishlagani')),
                ('skill', models.CharField(max_length=500, verbose_name="Ko'nikmalar")),
                ('expected_salary', models.CharField(max_length=600, verbose_name='Kutilayotgan oylik maosh miqdori (so‘m)')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Nomzod telefon raqami')),
                ('tg_username', models.CharField(max_length=50, verbose_name='Nomzod telegram username')),
                ('description', models.TextField(verbose_name='Nomzod ozi haqida batafsil')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Skill nomlari')),
            ],
        ),
    ]
