# Generated by Django 5.1.2 on 2024-12-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_offers',
            new_name='About_offers1',
        ),
    ]
