# Generated by Django 5.1.2 on 2024-12-19 23:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/image', verbose_name='Blog asosiy rasmini kiriting')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Blog sarlavhasini kiriting UZB')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Blog sarlavhasini kiriting RUS')),
                ('title_en', models.CharField(max_length=200, verbose_name='Blog sarlavhasini kiriting ENG')),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Blog matnini kiriting uz tilida')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Blog matnini kiriting ru tilida')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Blog matnini kiriting en tilida')),
                ('is_active', models.BooleanField(default=False, verbose_name="Asosiy sahifada ko'rinishi uchun aktivlashtiring")),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Bu yerga hech nima yozilmasin ')),
            ],
            options={
                'verbose_name': 'Bloglar',
                'verbose_name_plural': 'Bloglar',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Mijoz ismi')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefon raqami')),
                ('active', models.BooleanField(default=False, verbose_name="Bog'lanib bo'lgandan kn aktivlashtiring")),
            ],
            options={
                'verbose_name': 'Mijozlar arizalari',
                'verbose_name_plural': 'Mijozlar arizalari',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Kichik Sarlavha uzbek tilida')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Kichik Sarlavha rus tilida')),
                ('title_en', models.CharField(max_length=100, verbose_name='Kichik Sarlavha ingliz tilida')),
                ('subtitle_uz', models.CharField(max_length=100, verbose_name='Sarlavha uzbek tilida')),
                ('subtitle_ru', models.CharField(max_length=100, verbose_name='Sarlavha rus tilida')),
                ('subtitle_en', models.CharField(max_length=100, verbose_name='Sarlavha ingliz tilida')),
                ('logo', models.ImageField(upload_to='blog/image', verbose_name='Logo rasmini kiriting png holatda')),
                ('mini_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Saytning eng pastidagi matnni kiriting')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon raqam kiriting')),
                ('address_uz', models.CharField(max_length=50, verbose_name='Manzilni kiriting UZB')),
                ('address_ru', models.CharField(max_length=50, verbose_name='Manzilni kiriting RUS')),
                ('address_en', models.CharField(max_length=50, verbose_name='Manzilni kiriting ENG')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Video sarlavhasini kiriting UZB')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Video sarlavhasini kiriting RUS')),
                ('title_en', models.CharField(max_length=200, verbose_name='Video sarlavhasini kiriting ENG')),
                ('image', models.ImageField(upload_to='blog/image', verbose_name='Video uchun asosiy rasmini kiriting')),
                ('is_active', models.BooleanField(default=False, verbose_name="Asosiy sahifada ko'rinishi uchun aktivlashtiring")),
                ('link', models.CharField(max_length=200, verbose_name='Video linkini kiriting')),
            ],
            options={
                'verbose_name': 'Videolar',
                'verbose_name_plural': 'Videolar',
            },
        ),
    ]
