# Generated by Django 5.1.2 on 2024-11-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('yangi', 'yangi'), ('jarayonda', 'jarayonda'), ('intervyu_rejalashtirilgan', 'intervyu_rejalashtirilgan'), ('intervyu_qilingan', 'intervyu_qilingan'), ('taklif_berilgan', 'taklif_berilgan'), ('qabul_qilingan', 'qabul_qilingan'), ('rad_etilgan', 'rad_etilgan'), ('kutish', 'kutish')], default='yangi', max_length=200),
        ),
    ]
