# Generated by Django 5.1.2 on 2024-12-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_client_footer_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ijtimoiy sahifa nomini kiriitng')),
                ('link', models.CharField(max_length=100, verbose_name='Ijtimoiy sahifa linkini kiriitng')),
                ('icon', models.ImageField(upload_to='about/icon')),
            ],
            options={
                'verbose_name': 'Ijtimoiy sahifa',
                'verbose_name_plural': 'Ijtimoiy sahifa',
            },
        ),
    ]
