# Generated by Django 5.1.2 on 2024-12-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_about_offers_about_offers1'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_offers3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Kichik Sarlavha uzbek tilida')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Kichik Sarlavha rus tilida')),
                ('title_en', models.CharField(max_length=100, verbose_name='Kichik Sarlavha ingliz tilida')),
                ('subtitle_uz', models.CharField(max_length=100, verbose_name='Sarlavha uzbek tilida')),
                ('subtitle_ru', models.CharField(max_length=100, verbose_name='Sarlavha rus tilida')),
                ('subtitle_en', models.CharField(max_length=100, verbose_name='Sarlavha ingliz tilida')),
                ('icon', models.ImageField(upload_to='offers/icon', verbose_name='Icon biriktiring')),
            ],
            options={
                'verbose_name': 'About sahifasi uchun offers11',
                'verbose_name_plural': 'About sahifasi uchun offers11',
            },
        ),
    ]
