# Generated by Django 5.1.2 on 2024-12-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_imagefon_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailmini_en',
            field=models.TextField(default=1, verbose_name='Xususiyatlari (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='detailmini_ru',
            field=models.TextField(default=1, verbose_name='Xususiyatlari (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='detailmini_uz',
            field=models.TextField(default=1, verbose_name='Xususiyatlari (UZ)'),
            preserve_default=False,
        ),
    ]
