# Generated by Django 5.1.2 on 2024-12-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_offers3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_offers1',
        ),
    ]
