# Generated by Django 5.1.2 on 2024-12-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_titleheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_offers',
            fields=[
                ('offers2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.offers2')),
            ],
            options={
                'verbose_name': 'About Sahifasidagi yutuqlar',
                'verbose_name_plural': 'About Sahifasidagi yutuqlar',
            },
            bases=('main.offers2',),
        ),
    ]
