# Generated by Django 5.1.2 on 2024-12-13 19:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_about_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Kichik Sarlavha uzbek tilida')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Kichik Sarlavha rus tilida')),
                ('title_en', models.CharField(max_length=100, verbose_name='Kichik Sarlavha ingliz tilida')),
                ('subtitle_uz', models.CharField(max_length=100, verbose_name='Sarlavha uzbek tilida')),
                ('subtitle_ru', models.CharField(max_length=100, verbose_name='Sarlavha rus tilida')),
                ('subtitle_en', models.CharField(max_length=100, verbose_name='Sarlavha ingliz tilida')),
                ('mini_title_uz', models.CharField(max_length=300, verbose_name='mini matnlarni kiriitng UZB')),
                ('mini_title_ru', models.CharField(max_length=300, verbose_name='mini matnlarni kiriitng RUS')),
                ('mini_title_en', models.CharField(max_length=300, verbose_name='mini matnlarni kiriitng ENG')),
                ('description_uz', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Kompaniya haqida batafsil matnlarni kiriting uzb')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Kompaniya haqida batafsil matnlarni kiriting uzb')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Kompaniya haqida batafsil matnlarni kiriting uzb')),
                ('image', models.ImageField(upload_to='about/image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
