# Generated by Django 5.1.2 on 2024-12-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_miniabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutOfferTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Kichik Sarlavha uzbek tilida')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Kichik Sarlavha rus tilida')),
                ('title_en', models.CharField(max_length=100, verbose_name='Kichik Sarlavha ingliz tilida')),
                ('subtitle_uz', models.CharField(max_length=100, verbose_name='Sarlavha uzbek tilida')),
                ('subtitle_ru', models.CharField(max_length=100, verbose_name='Sarlavha rus tilida')),
                ('subtitle_en', models.CharField(max_length=100, verbose_name='Sarlavha ingliz tilida')),
            ],
            options={
                'verbose_name': 'Sarlavha Haqimizda ustunligimiz ',
                'verbose_name_plural': 'Sarlavha Haqimizda ustunligimiz ',
            },
        ),
    ]
