# Generated by Django 5.1.2 on 2024-12-13 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_aboutoffertitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Mijoz ismi uz tilida')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Mijoz ismi uz tilida')),
                ('comment_uz', models.TextField(verbose_name='Izoh matni uz tilida')),
                ('comment_ru', models.TextField(verbose_name='Izoh matni ru tilida')),
                ('comment_en', models.TextField(verbose_name='Izoh matni en tilida')),
                ('additional_uz', models.CharField(max_length=200, verbose_name="Qo'shimcha uz tilida")),
                ('additional_ru', models.CharField(max_length=200, verbose_name="Qo'shimca ru tilida")),
                ('additional_en', models.CharField(max_length=200, verbose_name="Qo'shimca en tilida")),
                ('image', models.ImageField(upload_to='comments/image')),
            ],
            options={
                'verbose_name': 'Mijozlar izohi',
                'verbose_name_plural': 'Mijozlar izohi',
            },
        ),
    ]
